# Generated by Django 5.2.8 on 2025-11-25 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metroline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In Use', 'In Use'), ('Used', 'Used'), ('Expired', 'Expired')], default='Active', max_length=10)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('entry_scan_time', models.DateTimeField(blank=True, null=True)),
                ('exit_scan_time', models.DateTimeField(blank=True, null=True)),
                ('end_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ending_tickets', to='metroline.station')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_tickets', to='metroline.station')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_in_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
