# Generated by Django 5.2.8 on 2025-11-25 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_purchasing_enabled', models.BooleanField(default=True, help_text='Controls the ability for passengers to buy new tickets on this line.')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order_on_line', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_operational', models.BooleanField(default=True, help_text='Controls if this station is open for service.')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroline.metroline')),
            ],
            options={
                'ordering': ['line', 'order_on_line'],
                'unique_together': {('line', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyFootfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entries', models.IntegerField(default=0)),
                ('exits', models.IntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metroline.station')),
            ],
            options={
                'unique_together': {('station', 'date')},
            },
        ),
    ]
